version: "3"

services:
  app: # 컨테이너1 : app
    build:
      context  : ./
      dockerfile: Dockerfile
    links:
      - "db:mysqldb"
    ports:
      - "80:8080"
    container_name: app
    depends_on:
      - db

  db: # 컨테이너2 : db
    image: mariadb:10.5.8
    volumes:
      - ./dbdata:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    container_name: db